### ISSUE TITLE
StringObject Showing error

### ISSUE THREAD

**Issue by sureshkona** [hemant3370/newsApp#1]
Hi

StringObject not resolved (Realm<StringObject>)

Cannot resolve a symbol "StringObject"
How to resolve it. Please help me.

**Comment by hemant3370** [comment]
The StringObject class is missing I guess. I will commit it soon.

**Comment by hemant3370** [comment]
Or you can do it yourself. RealmLists doesn't support simple strings yet. so you have to wrap each String into its own object:

You can see a work-around here: Gson deserialization of List<String> into realmList<RealmString>

or here: https://realm.io/docs/java/latest/#primitive-lists

**Comment by hemant3370** [comment]
@sureshkona  I have uploaded the file, you can import it where it's throwing that error.
